/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BayesX */

#ifndef _Included_BayesX
#define _Included_BayesX
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: LOCK */
/* Inaccessible static: dbg */
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef BayesX_TOP_ALIGNMENT
#define BayesX_TOP_ALIGNMENT 0.0f
#undef BayesX_CENTER_ALIGNMENT
#define BayesX_CENTER_ALIGNMENT 0.5f
#undef BayesX_BOTTOM_ALIGNMENT
#define BayesX_BOTTOM_ALIGNMENT 1.0f
#undef BayesX_LEFT_ALIGNMENT
#define BayesX_LEFT_ALIGNMENT 0.0f
#undef BayesX_RIGHT_ALIGNMENT
#define BayesX_RIGHT_ALIGNMENT 1.0f
#undef BayesX_serialVersionUID
#define BayesX_serialVersionUID -7644114512714619750LL
/* Inaccessible static: metrics */
/* Inaccessible static: class_00024java_00024awt_00024Component */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ComponentListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024FocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyBoundsListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024KeyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseMotionListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024InputMethodListener */
#undef BayesX_serialVersionUID
#define BayesX_serialVersionUID 4613797578919906343LL
/* Inaccessible static: dbg */
/* Inaccessible static: class_00024java_00024awt_00024Container */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ContainerListener */
#undef BayesX_OPENED
#define BayesX_OPENED 1L
/* Inaccessible static: nameCounter */
#undef BayesX_serialVersionUID
#define BayesX_serialVersionUID 4497834738069338734LL
/* Inaccessible static: dbg */
/* Inaccessible static: class_00024java_00024awt_00024Container */
/* Inaccessible static: class_00024java_00024awt_00024event_00024WindowListener */
#undef BayesX_DEFAULT_CURSOR
#define BayesX_DEFAULT_CURSOR 0L
#undef BayesX_CROSSHAIR_CURSOR
#define BayesX_CROSSHAIR_CURSOR 1L
#undef BayesX_TEXT_CURSOR
#define BayesX_TEXT_CURSOR 2L
#undef BayesX_WAIT_CURSOR
#define BayesX_WAIT_CURSOR 3L
#undef BayesX_SW_RESIZE_CURSOR
#define BayesX_SW_RESIZE_CURSOR 4L
#undef BayesX_SE_RESIZE_CURSOR
#define BayesX_SE_RESIZE_CURSOR 5L
#undef BayesX_NW_RESIZE_CURSOR
#define BayesX_NW_RESIZE_CURSOR 6L
#undef BayesX_NE_RESIZE_CURSOR
#define BayesX_NE_RESIZE_CURSOR 7L
#undef BayesX_N_RESIZE_CURSOR
#define BayesX_N_RESIZE_CURSOR 8L
#undef BayesX_S_RESIZE_CURSOR
#define BayesX_S_RESIZE_CURSOR 9L
#undef BayesX_W_RESIZE_CURSOR
#define BayesX_W_RESIZE_CURSOR 10L
#undef BayesX_E_RESIZE_CURSOR
#define BayesX_E_RESIZE_CURSOR 11L
#undef BayesX_HAND_CURSOR
#define BayesX_HAND_CURSOR 12L
#undef BayesX_MOVE_CURSOR
#define BayesX_MOVE_CURSOR 13L
#undef BayesX_NORMAL
#define BayesX_NORMAL 0L
#undef BayesX_ICONIFIED
#define BayesX_ICONIFIED 1L
/* Inaccessible static: nameCounter */
#undef BayesX_serialVersionUID
#define BayesX_serialVersionUID 2673458971256075116LL
/* Inaccessible static: class_00024java_00024awt_00024Frame */
#undef BayesX_EXIT_ON_CLOSE
#define BayesX_EXIT_ON_CLOSE 3L
/*
 * Class:     BayesX
 * Method:    getline
 * Signature: ([DIII)V
 */
JNIEXPORT void JNICALL Java_BayesX_getline
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jint);

/*
 * Class:     BayesX
 * Method:    getboundaries
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_BayesX_getboundaries
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     BayesX
 * Method:    getnrregions
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_BayesX_getnrregions
  (JNIEnv *, jobject);

/*
 * Class:     BayesX
 * Method:    getnrpoly
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_BayesX_getnrpoly
  (JNIEnv *, jobject, jint);

/*
 * Class:     BayesX
 * Method:    getnrlines
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_BayesX_getnrlines
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     BayesX
 * Method:    isin
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_BayesX_isin
  (JNIEnv *, jobject, jint);

/*
 * Class:     BayesX
 * Method:    getregionname
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_BayesX_getregionname
  (JNIEnv *, jobject, jint);

/*
 * Class:     BayesX
 * Method:    getcentroid
 * Signature: ([DI)V
 */
JNIEXPORT void JNICALL Java_BayesX_getcentroid
  (JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     BayesX
 * Method:    getname
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_BayesX_getname
  (JNIEnv *, jobject, jint);

/*
 * Class:     BayesX
 * Method:    setObjectList
 * Signature: (Ljava/util/Vector;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_BayesX_setObjectList
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     BayesX
 * Method:    setObjectTypeList
 * Signature: (Ljava/util/Vector;)V
 */
JNIEXPORT void JNICALL Java_BayesX_setObjectTypeList
  (JNIEnv *, jobject, jobject);

/*
 * Class:     BayesX
 * Method:    getValue
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_BayesX_getValue
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     BayesX
 * Method:    setVarnames
 * Signature: (Ljava/util/Vector;)V
 */
JNIEXPORT void JNICALL Java_BayesX_setVarnames
  (JNIEnv *, jobject, jobject);

/*
 * Class:     BayesX
 * Method:    getRows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_BayesX_getRows
  (JNIEnv *, jobject);

/*
 * Class:     BayesX
 * Method:    getDoubleValue
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_BayesX_getDoubleValue
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     BayesX
 * Method:    getDRows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_BayesX_getDRows
  (JNIEnv *, jobject);

/*
 * Class:     BayesX
 * Method:    getDCols
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_BayesX_getDCols
  (JNIEnv *, jobject);

/*
 * Class:     BayesX
 * Method:    getMax
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_BayesX_getMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     BayesX
 * Method:    getMin
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_BayesX_getMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     BayesX
 * Method:    getVarname
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_BayesX_getVarname
  (JNIEnv *, jobject, jint);

/*
 * Class:     BayesX
 * Method:    setStop
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_BayesX_setStop
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     BayesX
 * Method:    setPause
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_BayesX_setPause
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     BayesX
 * Method:    setProcessrunning
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_BayesX_setProcessrunning
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     BayesX
 * Method:    setSuppressoutput
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_BayesX_setSuppressoutput
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     BayesX
 * Method:    parse
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_BayesX_parse
  (JNIEnv *, jobject, jstring);

/*
 * Class:     BayesX
 * Method:    parsecommand
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_BayesX_parsecommand
  (JNIEnv *, jobject, jstring);

/*
 * Class:     BayesX
 * Method:    parsecommand2
 * Signature: (Ljavax/swing/JTextArea;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_BayesX_parsecommand2
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
